set nocompatible
filetype off

set rtp+=$HOME/.vim/bundle/vundle/
call vundle#rc()

Bundle 'gmarik/vundle'

let &t_Co=256
syntax enable

" all about surroundings
Bundle 'surround.vim'

" realtime keyword completion
Bundle 'Shougo/neocomplcache'
let g:neocomplcache_enable_at_startup = 1

" snippets
Bundle 'Shougo/neosnippet'
let g:neosnippet#snippets_directory = "~/.vim/snippets"
imap <C-k>     <Plug>(neosnippet_expand_or_jump)
smap <C-k>     <Plug>(neosnippet_expand_or_jump)

imap <expr><TAB> neosnippet#expandable() ? "\<Plug>(neosnippet_expand_or_jump)" : pumvisible() ? "\<C-n>" : "\<TAB>"
smap <expr><TAB> neosnippet#expandable() ? "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"

autocmd BufRead,BufNewFile *.snippets set filetype=snippet

" information widget
Bundle 'Shougo/unite.vim'
" start with insert mode
let g:unite_enable_start_insert = 1
nnoremap <silent> <C-f> :<C-u>UniteWithBufferDir -buffer-name=files file<CR>
inoremap <silent> <C-f> <ESC>:<C-u>UniteWithBufferDir -buffer-name=files file<CR>
nnoremap <silent> <C-b> :<C-u>Unite buffer file_mru<CR>
inoremap <silent> <C-b> <ESC>:<C-u>Unite buffer file_mru<CR>


" convert variable name style
" commands:
" crc -> hogeHoge
" crm -> HogeHoge
" cr_ -> hoge_hoge
" crs -> hoge_hoge
" cru -> HOGE_HOGE
Bundle 'tpope/vim-abolish'

Bundle 'kana/vim-fakeclip'

" textobj extension
Bundle 'kana/vim-textobj-user'

" treat indent as textobj
Bundle 'kana/vim-textobj-indent'

" comment out
Bundle 'tomtom/tcomment_vim'

" reference
Bundle 'thinca/vim-ref'

Bundle 'vim-scripts/guicolorscheme.vim'

" color schema
Bundle 'tomasr/molokai'
Bundle 'vim-scripts/Zenburn'
colorscheme zenburn
Bundle 'vim-scripts/Solarized'

" markdown
Bundle 'marcelinollano/vim-markdown'

" run code
Bundle 'thinca/vim-quickrun'

"""
""" Javascript bundles
" syntax highlight
Bundle 'JavaScript-syntax'

" indent
Bundle 'pangloss/vim-javascript'

"""
""" Python bundles
"""
" syntax and style cheker
Bundle 'nvie/vim-flake8'

" completion
Bundle 'pythoncomplete'

" module and class doc viewer
Bundle 'fs111/pydoc.vim'

" refactoring tools
" Bundle 'sontek/rope-vim'

"""
""" C++ bundles
"""
Bundle 'vim-scripts/google.vim'

"""
""" other settings
"""
nnoremap ; :

" .vimrc
nnoremap <silent> <Space>ev  :<C-u>edit $MYVIMRC<CR>
nnoremap <silent> <Space>rv :<C-u>source $MYVIMRC<CR>

" tab setting
setl tabstop=8
setl softtabstop=4
setl shiftwidth=4
setl smarttab
setl expandtab

" search setting
set hlsearch
set incsearch
nnoremap <ESC><ESC> :nohlsearch<CR>

" successive indent change in view mode
vnoremap < <gv
vnoremap > >gv

set tags=~/.tags

set wildmode=list:longest
filetype plugin indent on
set clipboard=unnamedplus
set backspace=indent,eol,start
set background=dark
set statusline=%f%m%r%h%w\%=\ [%{&ff}]%y[%{&enc}][%04l,%04v][%p%%]
set laststatus=2
set list
set listchars=tab:»-,trail:∇,eol:↲
